import type {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import type {Config} from './types.js';
import {registerAccountsList} from './accounts-list.js';
import {registerAccountBalanceGet} from './account-balance-get.js';
import {registerTransactionsList} from './transactions-list.js';
import {registerAccountHolderGet} from './account-holder-get.js';
import {registerPayeesList} from './payees-list.js';
import {registerAccountIdentifiersGet} from './account-identifiers-get.js';
import {registerCardsList} from './cards-list.js';
import {registerCardLockUpdate} from './card-lock-update.js';
import {registerDirectDebitsList} from './direct-debits-list.js';
import {registerStandingOrdersList} from './standing-orders-list.js';
import {registerFeedItemGet} from './feed-item-get.js';
import {registerFeedItemSpendingCategoryUpdate} from './feed-item-spending-category-update.js';
import {registerFeedItemNoteUpdate} from './feed-item-note-update.js';
import {registerFeedItemAttachmentDownload} from './feed-item-attachment-download.js';
import {registerPaymentCreate} from './payment-create.js';
import {registerPayeeCreate} from './payee-create.js';
import {registerPayeeDelete} from './payee-delete.js';
import {registerSavingsGoalsList} from './savings-goals-list.js';
import {registerSavingsGoalCreate} from './savings-goal-create.js';
import {registerSavingsGoalUpdate} from './savings-goal-update.js';
import {registerSavingsGoalDelete} from './savings-goal-delete.js';
import {registerSavingsGoalDeposit} from './savings-goal-deposit.js';
import {registerSavingsGoalWithdraw} from './savings-goal-withdraw.js';

export type {Config} from './types.js';

export function registerAll(server: McpServer, config: Config): void {
	registerAccountsList(server, config);
	registerAccountBalanceGet(server, config);
	registerTransactionsList(server, config);
	registerAccountHolderGet(server, config);
	registerPayeesList(server, config);
	registerAccountIdentifiersGet(server, config);
	registerCardsList(server, config);
	registerCardLockUpdate(server, config);
	registerDirectDebitsList(server, config);
	registerStandingOrdersList(server, config);
	registerFeedItemGet(server, config);
	registerFeedItemSpendingCategoryUpdate(server, config);
	registerFeedItemNoteUpdate(server, config);
	registerFeedItemAttachmentDownload(server, config);
	registerPaymentCreate(server, config);
	registerPayeeCreate(server, config);
	registerPayeeDelete(server, config);
	registerSavingsGoalsList(server, config);
	registerSavingsGoalCreate(server, config);
	registerSavingsGoalUpdate(server, config);
	registerSavingsGoalDelete(server, config);
	registerSavingsGoalDeposit(server, config);
	registerSavingsGoalWithdraw(server, config);
}
